// ── Key Term Store ───────────────────────────────────────────────────────
// Pure TypeScript — no DOM, no React, matching relationships.ts/search.ts's
// charter. Types for public/content/glossary.json, generated by
// scripts/build-glossary.mjs from scripts/lib/glossary-source.mjs (hand-
// curated definitions) enriched with usageCount/usedIn computed by scanning
// skillup notes for backtick-wrapped mentions — the same "curated source ->
// generated JSON with computed cross-content data" shape as taxonomy.json/
// relationships.json. Runtime loader lives in content-loader.ts
// (loadGlossaryMap), consumed via src/lib/useGlossary.ts.
// ────────────────────────────────────────────────────────────────────────

export interface GlossaryUsage {
  id: string;     // e.g. "exam/azure-ai-foundry" or "exam/ccaf/domain-1"
  title: string;
  url: string;
}

export interface GlossaryTermEntry {
  id: string;             // lowercase term, the lookup key
  term: string;           // display form as authored in glossary-source.mjs
  definition: string;
  usageCount: number;     // total backtick-wrapped mentions found across skillup notes
  usedIn: GlossaryUsage[]; // deduped by doc id
}

/** Shape of public/content/glossary.json. */
export interface GlossaryFile {
  schemaVersion: number;
  generated: string;
  terms: GlossaryTermEntry[];
}

/** Looks up `text` case-sensitively, then case-insensitively, in a loaded glossary map. */
export function lookupGlossaryTerm(
  map: Map<string, GlossaryTermEntry>,
  text: string
): GlossaryTermEntry | null {
  return map.get(text) ?? map.get(text.toLowerCase()) ?? null;
}
