// ── Study Plan types + generator ──────────────────────────────────────────────
// localStorage key: study_plan_{examId}
// Plan generation is pure (no AI API call in P1) — smart defaults from quiz scores.

import type { DomainConfig, QuizSession } from '@/types/content';

// ── Security: examId allowlist ─────────────────────────────────────────────
/** Only allow lowercase alphanumeric + hyphens to prevent key injection. */
const VALID_EXAM_ID = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export function isValidExamId(id: unknown): id is string {
  return typeof id === 'string' && VALID_EXAM_ID.test(id);
}

// ── Types ─────────────────────────────────────────────────────────────────────

export interface Activity {
  type: 'notes' | 'quiz' | 'review';
  label: string;
  link: string;
  estimatedMinutes: number;
  completed: boolean;
}

export interface StudySession {
  day: number;
  domainId: number;
  domainTitle: string;
  activities: Activity[];
  completed: boolean;
  estimatedMinutes: number;
  /** Optional tip from the AI mentor for this domain. */
  mentorNote?: string;
}

export interface StudyPlan {
  examId: string;
  targetDate: string;   // YYYY-MM-DD
  generatedAt: string;  // ISO timestamp
  sessions: StudySession[];
  /** Exam content version this plan was generated against (semver). */
  contentVersion?: string;
  /** True when this plan was generated by the AI mentor (not the static generator). */
  aiGenerated?: boolean;
}

// ── localStorage helpers ───────────────────────────────────────────────────────

function planKey(examId: string): string {
  return `study_plan_${examId}`;
}

export function loadPlan(examId: string): StudyPlan | null {
  if (!isValidExamId(examId)) return null;
  try {
    const raw = localStorage.getItem(planKey(examId));
    return raw ? (JSON.parse(raw) as StudyPlan) : null;
  } catch {
    return null;
  }
}

export function savePlan(plan: StudyPlan): void {
  if (!isValidExamId(plan.examId)) return;
  localStorage.setItem(planKey(plan.examId), JSON.stringify(plan));
}

export function deletePlan(examId: string): void {
  if (!isValidExamId(examId)) return;
  localStorage.removeItem(planKey(examId));
}

/** Return all study plans stored in localStorage keyed by examId. */
export function getAllStudyPlans(): Record<string, StudyPlan> {
  const result: Record<string, StudyPlan> = {};
  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (!key?.startsWith('study_plan_')) continue;
    const examId = key.slice('study_plan_'.length);
    if (!isValidExamId(examId)) continue;
    try {
      const raw = localStorage.getItem(key);
      if (raw) result[examId] = JSON.parse(raw) as StudyPlan;
    } catch { /* skip malformed entry */ }
  }
  return result;
}

export function toggleActivity(
  examId: string,
  sessionDay: number,
  activityIdx: number,
): StudyPlan | null {
  const plan = loadPlan(examId);
  if (!plan) return null;
  const session = plan.sessions.find((s) => s.day === sessionDay);
  if (!session || !session.activities[activityIdx]) return plan;
  session.activities[activityIdx] = {
    ...session.activities[activityIdx],
    completed: !session.activities[activityIdx].completed,
  };
  session.completed = session.activities.every((a) => a.completed);
  savePlan(plan);
  return { ...plan };
}

// ── Plan generation ────────────────────────────────────────────────────────────

type SessionType = 'review' | 'reinforce' | 'full';

function sessionType(pct: number, total: number): SessionType {
  if (total === 0) return 'full';
  if (pct >= 70) return 'review';
  return 'reinforce';
}

function buildActivities(
  type: SessionType,
  examId: string,
  domain: DomainConfig,
  dailyMinutes: number = 30,
): Activity[] {
  const n = domain.id;
  const notesLink = `/skillup/${examId}/notes?d=${n}`;
  const quizLink  = `/skillup/${examId}/quiz?domain=${n}`;
  const trapsLink = `/skillup/${examId}/notes?d=${n}#traps`;

  // 15 min budget: notes cheat-sheet only, quick quiz if space
  if (dailyMinutes <= 15) {
    return [
      { type: 'notes', label: `Read D${n} cheat-sheet`, link: notesLink, estimatedMinutes: 10, completed: false },
      { type: 'quiz',  label: 'Quick quiz — 5 Qs',       link: quizLink,  estimatedMinutes: 5,  completed: false },
    ];
  }

  // 60 min budget: full session with extra practice
  if (dailyMinutes >= 60) {
    return [
      { type: 'notes',  label: `Read D${n} Notes (full)`,  link: notesLink, estimatedMinutes: 20, completed: false },
      { type: 'quiz',   label: 'Domain quiz — 20 Qs',      link: quizLink,  estimatedMinutes: 15, completed: false },
      { type: 'review', label: 'Review Exam Traps',         link: trapsLink, estimatedMinutes: 10, completed: false },
      { type: 'quiz',   label: 'Timed practice — 10 Qs',   link: `${quizLink}&timed=1`, estimatedMinutes: 10, completed: false },
      { type: 'review', label: 'Self-test: explain each trap aloud', link: trapsLink, estimatedMinutes: 5, completed: false },
    ];
  }

  // 30 min budget (default): keep existing per-type logic
  if (type === 'review') {
    return [
      { type: 'notes',  label: `Read D${n} cheat-sheet`,  link: notesLink, estimatedMinutes: 10, completed: false },
      { type: 'quiz',   label: 'Quick quiz — 5 Qs',        link: quizLink,  estimatedMinutes: 5,  completed: false },
    ];
  }
  if (type === 'reinforce') {
    return [
      { type: 'notes',  label: `Read D${n} Notes`,        link: notesLink, estimatedMinutes: 15, completed: false },
      { type: 'quiz',   label: 'Domain quiz — 15 Qs',     link: quizLink,  estimatedMinutes: 10, completed: false },
      { type: 'review', label: 'Review Exam Traps',        link: trapsLink, estimatedMinutes: 5,  completed: false },
    ];
  }
  return [
    { type: 'notes',  label: `Read D${n} Notes`,        link: notesLink, estimatedMinutes: 25, completed: false },
    { type: 'quiz',   label: 'Domain quiz — 15 Qs',     link: quizLink,  estimatedMinutes: 15, completed: false },
    { type: 'review', label: 'Review Exam Traps',        link: trapsLink, estimatedMinutes: 5,  completed: false },
  ];
}

// ── Daily-minutes preference (localStorage) ──────────────────────────────────

const VALID_DAILY_MINS = [15, 30, 60] as const;
export type DailyMinutes = 15 | 30 | 60;

/** How many study sessions one domain needs at each daily-minute budget. */
const SESSIONS_PER_DOMAIN: Record<DailyMinutes, number> = { 15: 3, 30: 2, 60: 1 };

export function getDailyMinutesPref(examId: string): DailyMinutes {
  if (!isValidExamId(examId)) return 30;
  const raw = localStorage.getItem(`study_daily_mins_${examId}`);
  const n = Number(raw);
  return (VALID_DAILY_MINS as readonly number[]).includes(n) ? (n as DailyMinutes) : 30;
}

export function setDailyMinutesPref(examId: string, mins: DailyMinutes): void {
  if (!isValidExamId(examId)) return;
  localStorage.setItem(`study_daily_mins_${examId}`, String(mins));
}

// ── Weak-domain detection ─────────────────────────────────────────────────────

export interface WeakDomain {
  domainId: number;
  title: string;
  pct: number; // 0–100 average score
}

export function getWeakDomains(
  examId: string,
  domains: DomainConfig[],
  sessions: QuizSession[],
): WeakDomain[] {
  return domains
    .map((d) => {
      const domainSessions = sessions.filter(
        (s) => s.skillId === examId && s.finishedAt && s.domainFilter === d.id,
      );
      if (domainSessions.length === 0) return null;
      const correct = domainSessions.reduce((sum, s) => sum + s.score, 0);
      const total   = domainSessions.reduce((sum, s) => sum + s.total, 0);
      const pct = total > 0 ? Math.round((correct / total) * 100) : 0;
      return pct < 70 ? { domainId: d.id, title: d.title, pct } : null;
    })
    .filter((d): d is WeakDomain => d !== null)
    .sort((a, b) => a.pct - b.pct);
}

export interface DomainQuizScore {
  pct: number;
  attempts: number;
  lastScore: number; // most recent quiz raw score %
}

/** Compute per-domain quiz scores from session history. */
export function getQuizScoresByDomain(
  examId: string,
  domainIds: number[],
  sessions: QuizSession[],
): Record<number, DomainQuizScore> {
  const result: Record<number, DomainQuizScore> = {};
  for (const id of domainIds) {
    const ds = sessions.filter((s) => s.skillId === examId && s.finishedAt && s.domainFilter === id);
    if (ds.length === 0) { result[id] = { pct: 0, attempts: 0, lastScore: 0 }; continue; }
    const correct = ds.reduce((sum, s) => sum + s.score, 0);
    const total   = ds.reduce((sum, s) => sum + s.total, 0);
    const last = ds.sort((a, b) => (b.finishedAt ?? 0) - (a.finishedAt ?? 0))[0];
    result[id] = {
      pct: total > 0 ? Math.round((correct / total) * 100) : 0,
      attempts: ds.length,
      lastScore: last.total > 0 ? Math.round((last.score / last.total) * 100) : 0,
    };
  }
  return result;
}

/**
 * Scan quiz history and auto-mark plan activities as complete where evidence exists.
 * - Quiz activities: auto-complete if domain has ≥1 finished quiz session (any score).
 * - Notes activities: auto-complete if domain has ≥1 quiz attempt (implies notes were read).
 * Returns updated plan if any activity changed, null otherwise.
 */
export function autoSyncProgressToPlan(
  examId: string,
  sessions: QuizSession[],
): StudyPlan | null {
  const plan = loadPlan(examId);
  if (!plan) return null;
  let changed = false;

  for (const session of plan.sessions) {
    const ds = sessions.filter(
      (s) => s.skillId === examId && s.finishedAt && s.domainFilter === session.domainId,
    );
    if (ds.length === 0) continue;

    const correct = ds.reduce((sum, s) => sum + s.score, 0);
    const total   = ds.reduce((sum, s) => sum + s.total, 0);
    const pct = total > 0 ? Math.round((correct / total) * 100) : 0;

    for (const activity of session.activities) {
      if (activity.completed) continue;
      // Auto-complete quiz activities if any quiz taken for this domain
      if (activity.type === 'quiz' && ds.length > 0) {
        activity.completed = true;
        changed = true;
      }
      // Auto-complete notes activities if quiz was taken (implies notes were read) with ≥50%
      if (activity.type === 'notes' && pct >= 50) {
        activity.completed = true;
        changed = true;
      }
    }
    session.completed = session.activities.every((a) => a.completed);
  }

  if (!changed) return null;
  savePlan(plan);
  return { ...plan };
}

export interface GeneratePlanOptions {
  examId: string;
  domains: DomainConfig[];
  sessions: QuizSession[];
  targetDate: string; // YYYY-MM-DD
  dailyMinutes?: DailyMinutes;
  contentVersion?: string;
}

export function generatePlan({
  examId,
  domains,
  sessions,
  targetDate,
  dailyMinutes = 30,
  contentVersion,
}: GeneratePlanOptions): StudyPlan | null {
  if (!isValidExamId(examId)) return null;

  // Domain score map
  const scores: Record<number, { correct: number; total: number }> = {};
  for (const d of domains) scores[d.id] = { correct: 0, total: 0 };
  for (const s of sessions) {
    if (!s.finishedAt || s.skillId !== examId || s.domainFilter === null) continue;
    const sc = scores[s.domainFilter];
    if (sc) { sc.correct += s.score; sc.total += s.total; }
  }

  // Sort domains by weight descending — highest weight domain = Day 1
  const sorted = [...domains].sort((a, b) => b.weight - a.weight);

  const sessPerDomain = SESSIONS_PER_DOMAIN[dailyMinutes] ?? 1;

  // Build all sessions: each domain gets sessPerDomain sessions
  // with activities split across them, then assign sequential day numbers
  const studySessions: StudySession[] = [];
  let dayCounter = 1;

  for (const domain of sorted) {
    const sc = scores[domain.id];
    const pct = sc.total > 0 ? Math.round((sc.correct / sc.total) * 100) : 0;
    const type = sessionType(pct, sc.total);

    if (sessPerDomain === 1) {
      // 60 min: one rich session per domain
      const activities = buildActivities(type, examId, domain, dailyMinutes);
      studySessions.push({ day: dayCounter++, domainId: domain.id, domainTitle: `D${domain.id}: ${domain.title}`, activities, completed: false, estimatedMinutes: activities.reduce((s, a) => s + a.estimatedMinutes, 0) });
    } else if (sessPerDomain === 2) {
      // 30 min: session 1 = notes + light quiz; session 2 = full quiz + review
      const n = domain.id;
      const notesLink = `/skillup/${examId}/notes?d=${n}`;
      const quizLink  = `/skillup/${examId}/quiz?domain=${n}`;
      const trapsLink = `/skillup/${examId}/notes?d=${n}#traps`;
      const sess1: Activity[] = [
        { type: 'notes',  label: `Read D${n} Notes`,      link: notesLink, estimatedMinutes: 20, completed: false },
        { type: 'quiz',   label: 'Quick quiz — 5 Qs',     link: quizLink,  estimatedMinutes: 10, completed: false },
      ];
      const sess2: Activity[] = [
        { type: 'quiz',   label: 'Domain quiz — 15 Qs',   link: quizLink,  estimatedMinutes: 20, completed: false },
        { type: 'review', label: 'Review Exam Traps',      link: trapsLink, estimatedMinutes: 10, completed: false },
      ];
      studySessions.push({ day: dayCounter++, domainId: domain.id, domainTitle: `D${domain.id}: ${domain.title} (1/2)`, activities: sess1, completed: false, estimatedMinutes: 30 });
      studySessions.push({ day: dayCounter++, domainId: domain.id, domainTitle: `D${domain.id}: ${domain.title} (2/2)`, activities: sess2, completed: false, estimatedMinutes: 30 });
    } else {
      // 15 min: 3 sessions — read / quiz / review
      const n = domain.id;
      const notesLink = `/skillup/${examId}/notes?d=${n}`;
      const quizLink  = `/skillup/${examId}/quiz?domain=${n}`;
      const trapsLink = `/skillup/${examId}/notes?d=${n}#traps`;
      const sess1: Activity[] = [{ type: 'notes',  label: `Read D${n} cheat-sheet`,  link: notesLink, estimatedMinutes: 15, completed: false }];
      const sess2: Activity[] = [{ type: 'quiz',   label: 'Quick quiz — 5 Qs',       link: quizLink,  estimatedMinutes: 15, completed: false }];
      const sess3: Activity[] = [
        { type: 'review', label: 'Review Exam Traps',                   link: trapsLink, estimatedMinutes: 10, completed: false },
        { type: 'review', label: 'Self-test: explain each trap aloud',  link: trapsLink, estimatedMinutes: 5,  completed: false },
      ];
      studySessions.push({ day: dayCounter++, domainId: domain.id, domainTitle: `D${domain.id}: ${domain.title} — Notes`,  activities: sess1, completed: false, estimatedMinutes: 15 });
      studySessions.push({ day: dayCounter++, domainId: domain.id, domainTitle: `D${domain.id}: ${domain.title} — Quiz`,   activities: sess2, completed: false, estimatedMinutes: 15 });
      studySessions.push({ day: dayCounter++, domainId: domain.id, domainTitle: `D${domain.id}: ${domain.title} — Review`, activities: sess3, completed: false, estimatedMinutes: 15 });
    }
  }

  // If target date is very tight, compress (2 sessions/day)
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const target = new Date(targetDate); target.setHours(0, 0, 0, 0);
  const daysAvailable = Math.max(1, Math.round((target.getTime() - today.getTime()) / 86_400_000));
  const totalSessions = studySessions.length;

  if (daysAvailable < totalSessions) {
    // Repack: assign 2 sessions per day when tight
    studySessions.forEach((s, i) => { s.day = Math.ceil((i + 1) / 2); });
  }

  return { examId, targetDate, generatedAt: new Date().toISOString(), sessions: studySessions, contentVersion };
}

/** Returns true when sessions were compressed (2/day) due to a tight target date. */
export function isPlanCompressed(plan: StudyPlan): boolean {
  const uniqueDays = new Set(plan.sessions.map((s) => s.day)).size;
  return uniqueDays < plan.sessions.length;
}

/** First session that has at least one incomplete activity. */
export function nextIncompleteSession(plan: StudyPlan): StudySession | null {
  return plan.sessions.find((s) => !s.completed) ?? null;
}

/** Default target date: 4 weeks from today, YYYY-MM-DD. */
export function defaultTargetDate(): string {
  const d = new Date();
  d.setDate(d.getDate() + 28);
  return d.toISOString().split('T')[0];
}

// ── AI Plan builder ────────────────────────────────────────────────────────────

import type { MentorSession } from './mentor-api';

/**
 * Build a StudyPlan from AI mentor sessions.
 * The AI controls domain ordering and session types; this function constructs
 * the full plan using the same buildActivities() logic as generatePlan().
 */
export function buildAIPlan(
  examId: string,
  domains: DomainConfig[],
  mentorSessions: MentorSession[],
  targetDate: string,
  contentVersion?: string,
): StudyPlan | null {
  if (!isValidExamId(examId)) return null;

  const domainMap = new Map(domains.map((d) => [d.id, d]));

  // Filter to only valid domain IDs from the exam config
  const validSessions = mentorSessions.filter((ms) => domainMap.has(ms.domainId));
  if (validSessions.length === 0) return null;

  // Check if compression is needed
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const target = new Date(targetDate);
  target.setHours(0, 0, 0, 0);
  const daysAvailable = Math.max(1, Math.round((target.getTime() - today.getTime()) / 86_400_000));
  const compress = daysAvailable < validSessions.length;

  const studySessions: StudySession[] = validSessions.map((ms, idx) => {
    const domain = domainMap.get(ms.domainId)!;
    const activities = buildActivities(ms.sessionType, examId, domain);
    const estimatedMinutes = activities.reduce((sum, a) => sum + a.estimatedMinutes, 0);
    const day = compress ? Math.ceil((idx + 1) / 2) : idx + 1;
    return {
      day,
      domainId: domain.id,
      domainTitle: `D${domain.id}: ${domain.title}`,
      activities,
      completed: false,
      estimatedMinutes,
      mentorNote: ms.mentorNote,
    };
  });

  return {
    examId,
    targetDate,
    generatedAt: new Date().toISOString(),
    sessions: studySessions,
    contentVersion,
    aiGenerated: true,
  };
}
