import { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Server, Plus, Trash2, Copy, Check, ChevronDown, Info, Code2 } from 'lucide-react';

// ─── Types ────────────────────────────────────────────────────────────────────

type ParamType = 'string' | 'number' | 'boolean' | 'array' | 'object';

interface Param {
  id: string;
  name: string;
  type: ParamType;
  description: string;
  required: boolean;
}

interface ToolDef {
  id: string;
  name: string;
  description: string;
  params: Param[];
}

interface ServerConfig {
  name: string;
  version: string;
  description: string;
}

// ─── ID counter ───────────────────────────────────────────────────────────────

let idCounter = 0;
const uid = () => `id-${++idCounter}`;

// ─── Defaults ─────────────────────────────────────────────────────────────────

const defaultConfig: ServerConfig = {
  name: 'my-mcp-server',
  version: '1.0.0',
  description: 'A custom MCP server',
};

const defaultTool = (): ToolDef => ({
  id: uid(),
  name: 'get_data',
  description: 'Fetches data from the source',
  params: [
    { id: uid(), name: 'query', type: 'string', description: 'The search query', required: true },
  ],
});

const PARAM_TYPES: ParamType[] = ['string', 'number', 'boolean', 'array', 'object'];

// ─── Code generator ───────────────────────────────────────────────────────────

function toZodType(t: ParamType): string {
  switch (t) {
    case 'string': return 'z.string()';
    case 'number': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'array': return 'z.array(z.unknown())';
    case 'object': return 'z.record(z.unknown())';
  }
}

function toTsType(t: ParamType): string {
  switch (t) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return 'unknown[]';
    case 'object': return 'Record<string, unknown>';
  }
}

function sanitizeName(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, '_').replace(/^[0-9]/, '_$&') || 'unnamed';
}

function generateCode(config: ServerConfig, tools: ToolDef[]): string {
  const serverName = sanitizeName(config.name) || 'my-mcp-server';
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${serverName}`);
  if (config.description) lines.push(` * ${config.description}`);
  lines.push(` *`);
  lines.push(` * Generated by AI Architect Hub — MCP Scaffold`);
  lines.push(` * https://ajeetchouksey.github.io/ajch_platform/tools/mcp-scaffold`);
  lines.push(` */`);
  lines.push('');
  lines.push(`import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";`);
  lines.push(`import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";`);
  lines.push(`import { z } from "zod";`);
  lines.push('');
  lines.push(`// ─── Server ───────────────────────────────────────────────────`);
  lines.push('');
  lines.push(`const server = new McpServer({`);
  lines.push(`  name: "${serverName}",`);
  lines.push(`  version: "${sanitizeName(config.version) || '1.0.0'}",`);
  lines.push(`});`);
  lines.push('');

  if (tools.length > 0) {
    lines.push(`// ─── Tools ───────────────────────────────────────────────────`);
    lines.push('');

    for (const tool of tools) {
      const tName = sanitizeName(tool.name) || 'unnamed_tool';
      const hasParams = tool.params.length > 0;

      lines.push(`server.tool(`);
      lines.push(`  "${tName}",`);
      lines.push(`  "${tool.description.replace(/"/g, '\\"')}",`);

      if (hasParams) {
        lines.push(`  {`);
        for (const p of tool.params) {
          const pName = sanitizeName(p.name) || 'param';
          const zodExpr = p.required ? toZodType(p.type) : `${toZodType(p.type)}.optional()`;
          const descPart = p.description ? `.describe("${p.description.replace(/"/g, '\\"')}")` : '';
          lines.push(`    ${pName}: ${zodExpr}${descPart},`);
        }
        lines.push(`  },`);
      } else {
        lines.push(`  {},`);
      }

      // async handler
      if (hasParams) {
        const paramNames = tool.params
          .filter(p => p.required)
          .map(p => sanitizeName(p.name))
          .join(', ');
        const optionalParams = tool.params.filter(p => !p.required);
        const allParams = tool.params.map(p => sanitizeName(p.name)).join(', ');
        lines.push(`  async ({ ${allParams} }) => {`);
      } else {
        lines.push(`  async () => {`);
      }

      lines.push(`    // TODO: implement ${tName}`);
      lines.push(`    return {`);
      lines.push(`      content: [{ type: "text", text: \`${tName} executed successfully\` }],`);
      lines.push(`    };`);
      lines.push(`  }`);
      lines.push(`);`);
      lines.push('');
    }
  }

  lines.push(`// ─── Transport ───────────────────────────────────────────────`);
  lines.push('');
  lines.push(`const transport = new StdioServerTransport();`);
  lines.push(`await server.connect(transport);`);

  return lines.join('\n');
}

function generatePackageJson(config: ServerConfig): string {
  const name = sanitizeName(config.name) || 'my-mcp-server';
  const obj = {
    name,
    version: config.version || '1.0.0',
    description: config.description,
    type: 'module',
    main: 'dist/index.js',
    scripts: {
      build: 'tsc',
      start: 'node dist/index.js',
      dev: 'tsx src/index.ts',
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.12.0',
      zod: '^3.23.0',
    },
    devDependencies: {
      typescript: '^5.5.0',
      tsx: '^4.15.0',
      '@types/node': '^20.0.0',
    },
  };
  return JSON.stringify(obj, null, 2);
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);

  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs
        bg-slate-800/80 border border-slate-700/50 text-slate-400
        hover:text-violet-300 hover:border-violet-500/40 transition-all duration-150"
    >
      {copied ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
      {copied ? 'Copied!' : 'Copy'}
    </button>
  );
}

function ParamRow({
  param,
  onChange,
  onDelete,
}: {
  param: Param;
  onChange: (p: Param) => void;
  onDelete: () => void;
}) {
  return (
    <div className="grid grid-cols-[1fr_120px_1fr_auto_auto] gap-2 items-center">
      <input
        type="text"
        value={param.name}
        onChange={e => onChange({ ...param, name: e.target.value })}
        placeholder="param_name"
        className="bg-slate-900/60 border border-slate-700/50 rounded-lg px-3 py-1.5
          text-xs text-slate-300 placeholder:text-slate-600 focus:outline-none
          focus:border-violet-500/50 font-mono"
      />
      <select
        value={param.type}
        onChange={e => onChange({ ...param, type: e.target.value as ParamType })}
        className="bg-slate-900/60 border border-slate-700/50 rounded-lg px-2 py-1.5
          text-xs text-slate-400 focus:outline-none focus:border-violet-500/50"
      >
        {PARAM_TYPES.map(t => (
          <option key={t} value={t}>{t}</option>
        ))}
      </select>
      <input
        type="text"
        value={param.description}
        onChange={e => onChange({ ...param, description: e.target.value })}
        placeholder="Description"
        className="bg-slate-900/60 border border-slate-700/50 rounded-lg px-3 py-1.5
          text-xs text-slate-300 placeholder:text-slate-600 focus:outline-none
          focus:border-violet-500/50"
      />
      <button
        onClick={() => onChange({ ...param, required: !param.required })}
        aria-pressed={param.required}
        aria-label={`Mark ${param.name} as ${param.required ? 'optional' : 'required'}`}
        className={`px-2 py-1 rounded text-[10px] font-medium border transition-all duration-150 ${
          param.required
            ? 'bg-emerald-500/15 border-emerald-500/30 text-emerald-400'
            : 'bg-slate-800/60 border-slate-700/40 text-slate-500 hover:text-slate-400'
        }`}
      >
        {param.required ? 'req' : 'opt'}
      </button>
      <button
        onClick={onDelete}
        aria-label={`Delete parameter ${param.name}`}
        className="text-slate-600 hover:text-red-400 transition-colors"
      >
        <Trash2 size={12} />
      </button>
    </div>
  );
}

function ToolCard({
  tool,
  index,
  onChange,
  onDelete,
}: {
  tool: ToolDef;
  index: number;
  onChange: (t: ToolDef) => void;
  onDelete: () => void;
}) {
  const [collapsed, setCollapsed] = useState(false);

  const addParam = () =>
    onChange({
      ...tool,
      params: [
        ...tool.params,
        { id: uid(), name: 'param', type: 'string', description: '', required: true },
      ],
    });

  const updateParam = (id: string, p: Param) =>
    onChange({ ...tool, params: tool.params.map(x => (x.id === id ? p : x)) });

  const deleteParam = (id: string) =>
    onChange({ ...tool, params: tool.params.filter(x => x.id !== id) });

  return (
    <div className="glass-card rounded-xl border border-slate-800/50 overflow-hidden">
      {/* Tool header */}
      <div className="flex items-center gap-3 px-4 py-3 border-b border-slate-800/50">
        <span className="text-[10px] font-bold text-slate-600 font-mono w-5 shrink-0">
          T{index + 1}
        </span>
        <input
          type="text"
          value={tool.name}
          onChange={e => onChange({ ...tool, name: e.target.value })}
          placeholder="tool_name"
          className="flex-1 bg-transparent border-0 text-sm font-mono text-slate-300
            placeholder:text-slate-600 focus:outline-none focus:text-violet-200"
        />
        <button
          onClick={() => setCollapsed(v => !v)}
          aria-expanded={!collapsed}
          aria-label={collapsed ? 'Expand tool' : 'Collapse tool'}
          className="text-slate-600 hover:text-slate-400 transition-colors"
        >
          <ChevronDown size={14} className={`transition-transform duration-200 ${collapsed ? '-rotate-90' : ''}`} />
        </button>
        <button
          onClick={onDelete}
          aria-label={`Delete tool ${tool.name}`}
          className="text-slate-600 hover:text-red-400 transition-colors"
        >
          <Trash2 size={13} />
        </button>
      </div>

      {!collapsed && (
        <div className="px-4 py-3 space-y-3">
          <input
            type="text"
            value={tool.description}
            onChange={e => onChange({ ...tool, description: e.target.value })}
            placeholder="What does this tool do?"
            className="w-full bg-slate-900/60 border border-slate-700/50 rounded-lg px-3 py-2
              text-xs text-slate-300 placeholder:text-slate-600 focus:outline-none
              focus:border-violet-500/50"
          />

          {/* Parameters */}
          {tool.params.length > 0 && (
            <div className="space-y-2">
              <div className="grid grid-cols-[1fr_120px_1fr_auto_auto] gap-2 text-[10px] text-slate-600 uppercase tracking-wider px-0.5">
                <span>Name</span><span>Type</span><span>Description</span><span>Req</span><span />
              </div>
              {tool.params.map(p => (
                <ParamRow
                  key={p.id}
                  param={p}
                  onChange={updated => updateParam(p.id, updated)}
                  onDelete={() => deleteParam(p.id)}
                />
              ))}
            </div>
          )}

          <button
            onClick={addParam}
            className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-violet-300
              transition-colors"
          >
            <Plus size={12} />
            Add parameter
          </button>
        </div>
      )}
    </div>
  );
}

type Tab = 'index' | 'package';

// ─── MCP Docs ─────────────────────────────────────────────────────────────────

const MCP_DOCS = [
  {
    q: 'What is MCP?',
    a: 'The Model Context Protocol (MCP) is an open standard by Anthropic that lets AI models connect to external data sources and tools. An MCP server exposes "tools" (functions), "resources" (data), and "prompts" (templates) that any MCP-compatible client — including Claude Desktop — can use.',
    exam: 'CCA-F Domain 4 covers tool design and MCP. Expect questions on the server/client split: the MCP server owns the tool logic; the model decides when to call it.',
  },
  {
    q: 'What does server.tool() do?',
    a: 'server.tool(name, description, zodSchema, handler) registers a callable tool. The description is critical — Claude uses it to decide when to invoke the tool. The Zod schema defines the input contract and is surfaced to the model as a JSON Schema.',
    exam: 'Tool descriptions are part of the system context that consumes tokens. Keep descriptions concise but accurate — vague descriptions cause the model to misuse or ignore tools.',
  },
  {
    q: 'What transport should I use?',
    a: 'StdioServerTransport is the standard for local tools (Claude Desktop, Claude Code). Use it for desktop integrations. For remote/cloud tools, use SSEServerTransport (HTTP + Server-Sent Events) or the newer StreamableHTTP transport introduced in MCP 2025-03.',
    exam: 'CCA-F may ask you to identify the correct transport for a given scenario: local single-user tool → stdio, multi-user cloud service → SSE/StreamableHTTP.',
  },
  {
    q: 'Why Zod for schemas?',
    a: 'The MCP SDK uses Zod schemas to validate incoming tool arguments at runtime and to auto-generate the JSON Schema definition sent to the model. Optional parameters should use .optional(); add .describe() on every field — those descriptions appear in the model\'s tool call context.',
    exam: 'A missing .describe() on a required parameter is a common exam trap. The model cannot infer what to pass without a description.',
  },
  {
    q: 'How do I install and run an MCP server?',
    a: 'Add it to claude_desktop_config.json under mcpServers: { "my-server": { "command": "node", "args": ["dist/index.js"] } }. Run npm install && npm run build first. The server starts when Claude Desktop launches. For development, use tsx src/index.ts to skip the build step.',
    exam: 'The config file location varies by OS: macOS ~/Library/Application Support/Claude/, Windows %APPDATA%\\Claude\\. Claude Desktop must be restarted after config changes.',
  },
];

function McpDocs() {
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState<number | null>(null);

  return (
    <div className="glass-card rounded-xl border border-slate-800/50 overflow-hidden">
      <button
        onClick={() => setOpen(v => !v)}
        aria-expanded={open}
        className="w-full flex items-center justify-between px-5 py-4 text-left
          hover:bg-slate-800/30 transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <Info size={15} className="text-blue-400" />
          <span className="text-sm font-semibold text-slate-300">MCP Primer</span>
          <span className="text-[10px] text-slate-500 font-normal">— CCA-F Domain 4 study guide</span>
        </div>
        <ChevronDown size={14} className={`text-slate-500 transition-transform duration-200 ${open ? 'rotate-180' : ''}`} />
      </button>

      {open && (
        <div className="border-t border-slate-800/60 divide-y divide-slate-800/40">
          {MCP_DOCS.map((doc, i) => (
            <div key={i}>
              <button
                onClick={() => setExpanded(expanded === i ? null : i)}
                aria-expanded={expanded === i}
                className="w-full flex items-center justify-between px-5 py-3 text-left
                  hover:bg-slate-800/20 transition-colors gap-3"
              >
                <span className="text-sm text-slate-300 font-medium">{doc.q}</span>
                <ChevronDown size={12} className={`text-slate-600 shrink-0 transition-transform duration-200
                  ${expanded === i ? 'rotate-180' : ''}`} />
              </button>
              {expanded === i && (
                <div className="px-5 pb-4 space-y-2.5">
                  <p className="text-[12px] text-slate-400 leading-relaxed">{doc.a}</p>
                  {doc.exam && (
                    <div className="flex items-start gap-2 px-3 py-2.5 rounded-lg
                      bg-blue-500/5 border border-blue-500/20">
                      <span className="text-[9px] font-bold text-blue-400 uppercase tracking-widest
                        shrink-0 mt-0.5">Exam Tip</span>
                      <p className="text-[11px] text-blue-300/80 leading-relaxed">{doc.exam}</p>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function McpScaffold() {
  const [config, setConfig] = useState<ServerConfig>(defaultConfig);
  const [tools, setTools] = useState<ToolDef[]>([defaultTool()]);
  const [activeTab, setActiveTab] = useState<Tab>('index');

  const addTool = () =>
    setTools(prev => [...prev, { id: uid(), name: `tool_${prev.length + 1}`, description: '', params: [] }]);

  const updateTool = (id: string, t: ToolDef) =>
    setTools(prev => prev.map(x => (x.id === id ? t : x)));

  const deleteTool = (id: string) =>
    setTools(prev => prev.filter(x => x.id !== id));

  const reset = () => {
    setConfig(defaultConfig);
    setTools([defaultTool()]);
  };

  const generatedIndex = generateCode(config, tools);
  const generatedPackage = generatePackageJson(config);
  const activeCode = activeTab === 'index' ? generatedIndex : generatedPackage;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <nav className="flex items-center gap-2 text-xs text-slate-500 mb-4">
          <Link to="/tools" className="hover:text-violet-300 transition-colors">Tools</Link>
          <span className="text-slate-700">›</span>
          <span className="text-slate-400">MCP Scaffold</span>
        </nav>

        <div className="flex items-start gap-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20
            flex items-center justify-center shrink-0">
            <Server size={20} className="text-emerald-400" />
          </div>
          <div>
            <p className="page-eyebrow">Developer Tools</p>
            <h1 className="text-2xl font-bold tracking-tight">MCP <span className="heading-gradient">Scaffold</span></h1>
            <p className="text-slate-400 text-sm mt-1">
              Generate MCP server boilerplate from a config spec. Zero setup — just copy and run.
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {/* ── Left: Config ── */}
        <div className="space-y-4">
          {/* Server config */}
          <div className="glass-card rounded-xl border border-slate-800/50 p-4 space-y-3">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Server</p>
            <div className="grid grid-cols-[1fr_120px] gap-3">
              <div className="space-y-1">
                <label className="text-[10px] text-slate-600 uppercase tracking-wider">Name</label>
                <input
                  type="text"
                  value={config.name}
                  onChange={e => setConfig(c => ({ ...c, name: e.target.value }))}
                  placeholder="my-mcp-server"
                  className="w-full bg-slate-900/60 border border-slate-700/50 rounded-lg px-3 py-2
                    text-sm text-slate-300 placeholder:text-slate-600 font-mono
                    focus:outline-none focus:border-emerald-500/50"
                />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] text-slate-600 uppercase tracking-wider">Version</label>
                <input
                  type="text"
                  value={config.version}
                  onChange={e => setConfig(c => ({ ...c, version: e.target.value }))}
                  placeholder="1.0.0"
                  className="w-full bg-slate-900/60 border border-slate-700/50 rounded-lg px-3 py-2
                    text-sm text-slate-300 placeholder:text-slate-600 font-mono
                    focus:outline-none focus:border-emerald-500/50"
                />
              </div>
            </div>
            <div className="space-y-1">
              <label className="text-[10px] text-slate-600 uppercase tracking-wider">Description</label>
              <input
                type="text"
                value={config.description}
                onChange={e => setConfig(c => ({ ...c, description: e.target.value }))}
                placeholder="What does your server do?"
                className="w-full bg-slate-900/60 border border-slate-700/50 rounded-lg px-3 py-2
                  text-sm text-slate-300 placeholder:text-slate-600
                  focus:outline-none focus:border-emerald-500/50"
              />
            </div>
          </div>

          {/* Tools */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">
                Tools <span className="text-slate-700 font-normal normal-case">({tools.length})</span>
              </p>
              <div className="flex items-center gap-2">
                <button
                  onClick={reset}
                  className="text-xs text-slate-600 hover:text-slate-400 transition-colors"
                >
                  Reset
                </button>
                <button
                  onClick={addTool}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs
                    bg-emerald-500/10 border border-emerald-500/20 text-emerald-400
                    hover:bg-emerald-500/15 transition-all duration-150"
                >
                  <Plus size={12} />
                  Add Tool
                </button>
              </div>
            </div>

            {tools.map((tool, idx) => (
              <ToolCard
                key={tool.id}
                tool={tool}
                index={idx}
                onChange={updated => updateTool(tool.id, updated)}
                onDelete={() => deleteTool(tool.id)}
              />
            ))}

            {tools.length === 0 && (
              <div className="text-center py-8 text-slate-600 text-sm border border-dashed border-slate-800/60 rounded-xl">
                No tools defined — add at least one tool
              </div>
            )}
          </div>

          {/* Docs */}
          <McpDocs />
        </div>

        {/* ── Right: Generated code ── */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Generated</p>
            <CopyButton text={activeCode} />
          </div>

          {/* File tabs */}
          <div className="flex gap-1 p-1 bg-slate-900/40 rounded-lg border border-slate-800/50 w-fit">
            {(['index', 'package'] as Tab[]).map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                aria-pressed={activeTab === tab}
                className={`px-3 py-1 rounded-md text-xs font-medium transition-all duration-150 ${
                  activeTab === tab
                    ? 'bg-emerald-500/15 border border-emerald-500/30 text-emerald-300'
                    : 'text-slate-500 hover:text-slate-400'
                }`}
              >
                {tab === 'index' ? 'src/index.ts' : 'package.json'}
              </button>
            ))}
          </div>

          {/* Code block */}
          <div className="glass-card rounded-xl border border-slate-800/50 overflow-hidden">
            <div className="flex items-center gap-2 px-4 py-2.5 border-b border-slate-800/50 bg-slate-900/30">
              <Code2 size={13} className="text-emerald-400" />
              <span className="text-xs text-slate-500 font-mono">
                {activeTab === 'index' ? 'src/index.ts' : 'package.json'}
              </span>
            </div>
            <pre className="p-4 text-[11px] leading-relaxed text-slate-300 font-mono overflow-x-auto max-h-[620px] overflow-y-auto">
              <code>{activeCode}</code>
            </pre>
          </div>

          {/* Install instructions */}
          <div className="glass-card rounded-xl border border-slate-800/50 p-4 space-y-2">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Quick Start</p>
            <div className="space-y-1.5 text-[11px] text-slate-400 font-mono">
              <p className="text-slate-600"># 1. Save the files and install deps</p>
              <p>npm install</p>
              <p className="text-slate-600"># 2. Build</p>
              <p>npm run build</p>
              <p className="text-slate-600"># 3. Add to Claude Desktop config</p>
              <p className="text-slate-500">{'{'}</p>
              <p className="pl-4 text-slate-500">{`"mcpServers": {`}</p>
              <p className="pl-8 text-slate-400">{`"${sanitizeName(config.name)}": {`}</p>
              <p className="pl-12 text-slate-400">{`"command": "node",`}</p>
              <p className="pl-12 text-slate-400">{`"args": ["dist/index.js"]`}</p>
              <p className="pl-8 text-slate-500">{'}'}</p>
              <p className="pl-4 text-slate-500">{'}'}</p>
              <p className="text-slate-500">{'}'}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
