import { useState, useRef } from 'react';
import type { GlossaryTermEntry } from '@/lib/glossary';

// ── Inline key-term tooltip ─────────────────────────────────────────────────
// Shared by every markdown-rendering surface that wants inline term
// definitions (exam Notes.tsx, SkillTrackHome.tsx lesson notes). Definitions
// themselves are NOT hardcoded here — they're loaded at runtime from
// public/content/glossary.json (src/lib/useGlossary.ts), generated by
// scripts/build-glossary.mjs from the curated scripts/lib/glossary-source.mjs
// dictionary, the same "curated source -> generated JSON enriched with
// computed cross-content data" shape as this platform's taxonomy/
// relationships content-intelligence pipeline (IDEA-0008) — so a term's
// "used in N other lesson(s)" relation and count travel with it instead of
// living only in one page's local knowledge.
export function TermTooltip({ entry }: { entry: GlossaryTermEntry }) {
  const [visible, setVisible] = useState(false);
  const [pos, setPos] = useState<{ left: number; flipped: boolean; caretLeft: number } | null>(null);
  const ref = useRef<HTMLElement>(null);
  const TIP_W = 280;

  const handleShow = () => {
    if (ref.current) {
      const rect = ref.current.getBoundingClientRect();
      const vw = window.innerWidth;
      const header = document.querySelector('header');
      const headerBottom = header ? header.getBoundingClientRect().bottom : 64;
      const flipped = rect.top < headerBottom + 130;
      const ideal = rect.left + rect.width / 2 - TIP_W / 2;
      const clamped = Math.max(8, Math.min(vw - TIP_W - 8, ideal));
      const left = clamped - rect.left;
      const caretLeft = Math.max(12, Math.min(TIP_W - 16, rect.width / 2 - left));
      setPos({ left, flipped, caretLeft });
    }
    setVisible(true);
  };

  const tipY: React.CSSProperties = pos?.flipped
    ? { top: 'calc(100% + 6px)', bottom: 'auto' }
    : { bottom: 'calc(100% + 6px)', top: 'auto' };

  return (
    <code
      ref={ref as React.RefObject<HTMLElement>}
      className="cursor-help"
      style={{ textDecorationLine: 'underline', textDecorationStyle: 'dotted', textDecorationColor: 'rgba(167,139,250,0.8)', textUnderlineOffset: '2px', position: 'relative' }}
      onMouseEnter={handleShow}
      onMouseLeave={() => setVisible(false)}
    >
      {entry.term}
      {visible && pos && (
        <span
          role="tooltip"
          style={{
            position: 'absolute',
            ...tipY,
            left: `${pos.left}px`,
            width: `${TIP_W}px`,
            zIndex: 60,
            background: 'rgba(9,18,36,0.98)',
            border: '1px solid rgba(167,139,250,0.35)',
            borderRadius: '10px',
            padding: '8px 12px',
            pointerEvents: 'none',
            boxShadow: '0 8px 32px rgba(0,0,0,0.65)',
            backdropFilter: 'blur(8px)',
            whiteSpace: 'normal',
            fontFamily: 'Inter, system-ui, sans-serif',
            fontSize: '12px',
            fontStyle: 'normal',
            fontWeight: 400,
            lineHeight: 1.55,
            letterSpacing: 'normal',
            textDecorationLine: 'none',
            color: '#94a3b8',
          } as React.CSSProperties}
        >
          <span style={{ display: 'block', fontFamily: 'monospace', fontSize: '10px', fontWeight: 900, textTransform: 'uppercase', letterSpacing: '0.18em', color: '#a78bfa', background: 'rgba(167,139,250,0.12)', border: '1px solid rgba(167,139,250,0.3)', borderRadius: '4px', padding: '1px 6px', marginBottom: '6px' }}>
            key term
          </span>
          {entry.definition}
          {entry.usedIn.length > 0 && (
            <span style={{ display: 'block', marginTop: '8px', paddingTop: '6px', borderTop: '1px solid rgba(148,163,184,0.15)' }}>
              <span style={{ display: 'block', fontSize: '10px', fontWeight: 700, color: '#64748b', marginBottom: '2px' }}>
                Used in {entry.usedIn.length} place{entry.usedIn.length === 1 ? '' : 's'} across Skill Up
              </span>
              {entry.usedIn.slice(0, 3).map((u) => (
                <span key={u.id} style={{ display: 'block', fontSize: '10.5px', color: '#94a3b8', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  · {u.title}
                </span>
              ))}
            </span>
          )}
          {/* caret */}
          <span style={{ position: 'absolute', left: `${pos.caretLeft}px`, ...(pos.flipped ? { top: '-5px', borderTop: '1px solid rgba(167,139,250,0.35)', borderLeft: '1px solid rgba(167,139,250,0.35)' } : { bottom: '-5px', borderBottom: '1px solid rgba(167,139,250,0.35)', borderRight: '1px solid rgba(167,139,250,0.35)' }), transform: 'rotate(45deg)', width: '9px', height: '9px', background: 'rgba(9,18,36,0.98)' }} />
        </span>
      )}
    </code>
  );
}
