/**
 * content-sources.mjs
 *
 * Shared build-time content loaders for scripts/generate-og-shells.mjs and
 * scripts/generate-sitemap.mjs. Manifest-aware: reads from the CDN-promoted
 * vertical repo when content-manifest.json has an entry for it, else falls
 * back to the local public/content/{vertical} mirror. Mirrors
 * src/lib/content-manifest.ts's resolution rule (reimplemented here — that
 * module is browser-oriented).
 */

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..', '..');
const contentDir = join(root, 'public', 'content');
const manifestPath = join(root, 'content-manifest.json');

function loadManifest() {
  if (!existsSync(manifestPath)) return null;
  return JSON.parse(readFileSync(manifestPath, 'utf-8'));
}

// content-manifest.json is CODEOWNERS-gated, but it's still file data that ends up
// driving an outbound fetch URL — validate its shape before trusting it, rather than
// interpolating repo/sha/baseUrl directly (CodeQL js/file-access-to-http).
const GITHUB_REPO_PATTERN = /^[\w.-]+\/[\w.-]+$/;
const SHA_PATTERN = /^[0-9a-f]{7,40}$/i;
const ALLOWED_BASE_URLS = new Set(['https://cdn.jsdelivr.net/gh']);

function resolveCdnBase(entry, vertical) {
  if (!entry?.repo || !GITHUB_REPO_PATTERN.test(entry.repo)) {
    throw new Error(`content-manifest.json: invalid repo for "${vertical}": ${JSON.stringify(entry?.repo)}`);
  }
  if (!entry?.sha || !SHA_PATTERN.test(entry.sha)) {
    throw new Error(`content-manifest.json: invalid sha for "${vertical}": ${JSON.stringify(entry?.sha)}`);
  }
  const baseUrl = (entry.baseUrl ?? 'https://cdn.jsdelivr.net/gh').replace(/\/$/, '');
  if (!ALLOWED_BASE_URLS.has(baseUrl)) {
    throw new Error(`content-manifest.json: baseUrl not in allowlist for "${vertical}": ${JSON.stringify(baseUrl)}`);
  }
  return baseUrl;
}

async function fetchFromCdn(entry, contentPath, label, vertical) {
  const baseUrl = resolveCdnBase(entry, vertical);
  const url = `${baseUrl}/${entry.repo}@${entry.sha}/${contentPath}`;
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`✗ ${label}: could not fetch ${url} — HTTP ${res.status}`);
    process.exit(1);
  }
  return res.json();
}

// blog/index.json — CDN when promoted, else local.
export async function loadBlogIndex() {
  const manifest = loadManifest();
  const blog = manifest?.blog;
  if (blog?.repo && blog?.sha) {
    return fetchFromCdn(blog, 'content/blog/index.json', 'loadBlogIndex', 'blog');
  }
  return JSON.parse(readFileSync(join(contentDir, 'blog', 'index.json'), 'utf-8'));
}

// skillup/catalog.json — CDN when promoted, else local. May legitimately not
// exist yet in a fresh local checkout (generated by ajch_skillup's own
// scripts/generate-catalog.py once promoted, or scripts/build-content-
// intelligence.mjs's local fallback before that), so the local branch stays
// tolerant of a missing file; the CDN branch still fails loudly on fetch
// failure, matching the stricter behavior for a
// promoted vertical.
export async function loadSkillupCatalog() {
  const manifest = loadManifest();
  const skillup = manifest?.skillup;
  if (skillup?.repo && skillup?.sha) {
    return fetchFromCdn(skillup, 'content/skillup/catalog.json', 'loadSkillupCatalog', 'skillup');
  }
  const localPath = join(contentDir, 'skillup', 'catalog.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// One skillup question file (path already looks like "content/skillup/
// {examId}/questions/{examId}-domain{N}.json", exactly as stored in each
// exam's questionFiles[]) — CDN when skillup is promoted, else local.
export async function loadSkillupQuestionFile(relativePath) {
  const manifest = loadManifest();
  const skillup = manifest?.skillup;
  if (skillup?.repo && skillup?.sha) {
    return fetchFromCdn(skillup, relativePath, 'loadSkillupQuestionFile', 'skillup');
  }
  const localPath = join(root, 'public', relativePath);
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// One skillup lesson/domain note file, as plain markdown text (path already
// looks like "content/skillup/{examId}/notes/{file}.md", exactly as stored
// in a domain's/lesson's notesFile) — CDN when skillup is promoted, else
// local. Unlike fetchFromCdn's other callers, a missing/renamed note here
// is non-fatal: it means one glossary-usage data point is skipped, not that
// the whole content-intelligence build should abort (see build-glossary.mjs).
async function fetchTextFromCdn(entry, contentPath) {
  const baseUrl = resolveCdnBase(entry, 'skillup');
  const url = `${baseUrl}/${entry.repo}@${entry.sha}/${contentPath}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url}`);
  return res.text();
}

export async function loadSkillupNoteFile(relativePath) {
  const manifest = loadManifest();
  const skillup = manifest?.skillup;
  if (skillup?.repo && skillup?.sha) {
    return fetchTextFromCdn(skillup, relativePath);
  }
  const localPath = join(root, 'public', relativePath);
  if (!existsSync(localPath)) return null;
  return readFileSync(localPath, 'utf-8');
}

// interviews/index.json — not yet a promoted vertical, always local.
export async function loadInterviewsIndex() {
  const localPath = join(contentDir, 'interviews', 'index.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// interviews/bank/questions.json — the actual tagged question items (index.json
// above is just the role-pack index). Not yet a promoted vertical, always local.
export async function loadInterviewsBank() {
  const localPath = join(contentDir, 'interviews', 'bank', 'questions.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// usecases/_source-intel.json — CDN when promoted, else local.
export async function loadUsecasesSourceIntel() {
  const manifest = loadManifest();
  const usecases = manifest?.usecases;
  if (usecases?.repo && usecases?.sha) {
    return fetchFromCdn(usecases, 'content/usecases/_source-intel.json', 'loadUsecasesSourceIntel', 'usecases');
  }
  const localPath = join(contentDir, 'usecases', '_source-intel.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// usecases/index.json (distinct from _source-intel.json above) — carries the
// canonical patterns[] catalog ({id, label, count}), already taxonomy-shaped.
// CDN when promoted, else local.
export async function loadUsecasesIndex() {
  const manifest = loadManifest();
  const usecases = manifest?.usecases;
  if (usecases?.repo && usecases?.sha) {
    return fetchFromCdn(usecases, 'content/usecases/index.json', 'loadUsecasesIndex', 'usecases');
  }
  const localPath = join(contentDir, 'usecases', 'index.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// Every content/usecases/cases/{id}.json file that exists in the promoted
// repo, discovered via jsDelivr's data API (a real directory listing, not
// GitHub's own API — no token needed, same trust boundary as the raw-file
// CDN already used everywhere else in this file). Closes the permanent
// sync-drift risk collectRelDocs() otherwise has: a case file this list
// finds that _source-intel.json's summary arrays don't mention is exactly
// the "invisible forever, not just until the next backfill run" gap
// ajch_food_for_thoughts#40 was filed to close. Local (non-promoted) mode
// just reads the directory directly — no network call needed.
export async function listUsecasesCaseFileIds() {
  const manifest = loadManifest();
  const usecases = manifest?.usecases;
  if (usecases?.repo && usecases?.sha) {
    resolveCdnBase(usecases, 'usecases'); // validates repo/sha shape before use, same as every other CDN call here
    const url = `https://data.jsdelivr.com/v1/packages/gh/${usecases.repo}@${usecases.sha}?structure=flat`;
    const res = await fetch(url);
    if (!res.ok) {
      console.error(`⚠ listUsecasesCaseFileIds: could not list ${url} — HTTP ${res.status}`);
      return [];
    }
    const data = await res.json();
    return (data.files ?? [])
      .filter((f) => f.name.startsWith('/content/usecases/cases/') && f.name.endsWith('.json'))
      .map((f) => f.name.slice('/content/usecases/cases/'.length, -'.json'.length));
  }
  const localDir = join(contentDir, 'usecases', 'cases');
  if (!existsSync(localDir)) return [];
  return readdirSync(localDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.slice(0, -'.json'.length));
}

// One individual content/usecases/cases/{id}.json file — CDN when promoted,
// else local. Non-fatal on a missing/unreadable file (returns null) —
// deliberately NOT fetchFromCdn, whose HTTP-error path is process.exit(1)
// (uncatchable by a try/catch around the call). This is only ever called for
// an id listUsecasesCaseFileIds() found but _source-intel.json didn't
// summarize, an edge case that should degrade to "skip this one doc," not
// abort the whole content-intelligence build.
export async function loadUsecaseCaseFile(id) {
  const manifest = loadManifest();
  const usecases = manifest?.usecases;
  try {
    if (usecases?.repo && usecases?.sha) {
      const baseUrl = resolveCdnBase(usecases, 'usecases');
      const url = `${baseUrl}/${usecases.repo}@${usecases.sha}/content/usecases/cases/${id}.json`;
      const res = await fetch(url);
      if (!res.ok) return null;
      return await res.json();
    }
    const localPath = join(contentDir, 'usecases', 'cases', `${id}.json`);
    if (!existsSync(localPath)) return null;
    return JSON.parse(readFileSync(localPath, 'utf-8'));
  } catch {
    return null;
  }
}

// hol-labs/index.json — CDN when promoted, else local. Manifest key is
// "hol-labs" (matches content-manifest.json), not "holLabs" or "hollabs".
export async function loadHolLabsIndex() {
  const manifest = loadManifest();
  const holLabs = manifest?.['hol-labs'];
  if (holLabs?.repo && holLabs?.sha) {
    return fetchFromCdn(holLabs, 'content/hol-labs/index.json', 'loadHolLabsIndex', 'hol-labs');
  }
  const localPath = join(contentDir, 'hol-labs', 'index.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// hol-labs/labs/{id}.json — a single full lab file, CDN when promoted, else
// local. Only the index.json summary is needed for most purposes (that's
// the whole point of HolLabSummary) — this exists specifically for reading
// the full relatedExams/relatedBlogPosts/relatedUseCases `why` text, which
// isn't flattened into the summary. Fine to call once per lab at this
// vertical's current size; revisit if it ever grows into the hundreds.
export async function loadHolLabFile(id) {
  const manifest = loadManifest();
  const holLabs = manifest?.['hol-labs'];
  if (holLabs?.repo && holLabs?.sha) {
    return fetchFromCdn(holLabs, `content/hol-labs/labs/${id}.json`, 'loadHolLabFile', 'hol-labs');
  }
  const localPath = join(contentDir, 'hol-labs', 'labs', `${id}.json`);
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}
