/**
 * content-sources.mjs
 *
 * Shared build-time content loaders for scripts/generate-og-shells.mjs and
 * scripts/generate-sitemap.mjs. Manifest-aware: reads from the CDN-promoted
 * vertical repo when content-manifest.json has an entry for it, else falls
 * back to the local public/content/{vertical} mirror. Mirrors
 * src/lib/content-manifest.ts's resolution rule (reimplemented here — that
 * module is browser-oriented).
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..', '..');
const contentDir = join(root, 'public', 'content');
const manifestPath = join(root, 'content-manifest.json');

function loadManifest() {
  if (!existsSync(manifestPath)) return null;
  return JSON.parse(readFileSync(manifestPath, 'utf-8'));
}

// content-manifest.json is CODEOWNERS-gated, but it's still file data that ends up
// driving an outbound fetch URL — validate its shape before trusting it, rather than
// interpolating repo/sha/baseUrl directly (CodeQL js/file-access-to-http).
const GITHUB_REPO_PATTERN = /^[\w.-]+\/[\w.-]+$/;
const SHA_PATTERN = /^[0-9a-f]{7,40}$/i;
const ALLOWED_BASE_URLS = new Set(['https://cdn.jsdelivr.net/gh']);

function resolveCdnBase(entry, vertical) {
  if (!entry?.repo || !GITHUB_REPO_PATTERN.test(entry.repo)) {
    throw new Error(`content-manifest.json: invalid repo for "${vertical}": ${JSON.stringify(entry?.repo)}`);
  }
  if (!entry?.sha || !SHA_PATTERN.test(entry.sha)) {
    throw new Error(`content-manifest.json: invalid sha for "${vertical}": ${JSON.stringify(entry?.sha)}`);
  }
  const baseUrl = (entry.baseUrl ?? 'https://cdn.jsdelivr.net/gh').replace(/\/$/, '');
  if (!ALLOWED_BASE_URLS.has(baseUrl)) {
    throw new Error(`content-manifest.json: baseUrl not in allowlist for "${vertical}": ${JSON.stringify(baseUrl)}`);
  }
  return baseUrl;
}

async function fetchFromCdn(entry, contentPath, label, vertical) {
  const baseUrl = resolveCdnBase(entry, vertical);
  const url = `${baseUrl}/${entry.repo}@${entry.sha}/${contentPath}`;
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`✗ ${label}: could not fetch ${url} — HTTP ${res.status}`);
    process.exit(1);
  }
  return res.json();
}

// blog/index.json — CDN when promoted, else local.
export async function loadBlogIndex() {
  const manifest = loadManifest();
  const blog = manifest?.blog;
  if (blog?.repo && blog?.sha) {
    return fetchFromCdn(blog, 'content/blog/index.json', 'loadBlogIndex', 'blog');
  }
  return JSON.parse(readFileSync(join(contentDir, 'blog', 'index.json'), 'utf-8'));
}

// skillup/catalog.json — CDN when promoted, else local. May legitimately not
// exist yet in a fresh local checkout (generated by scripts/sync-stats.py),
// so the local branch stays tolerant of a missing file; the CDN branch still
// fails loudly on fetch failure, matching the stricter behavior for a
// promoted vertical.
export async function loadSkillupCatalog() {
  const manifest = loadManifest();
  const skillup = manifest?.skillup;
  if (skillup?.repo && skillup?.sha) {
    return fetchFromCdn(skillup, 'content/skillup/catalog.json', 'loadSkillupCatalog', 'skillup');
  }
  const localPath = join(contentDir, 'skillup', 'catalog.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// interviews/index.json — not yet a promoted vertical, always local.
export async function loadInterviewsIndex() {
  const localPath = join(contentDir, 'interviews', 'index.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}

// usecases/_source-intel.json — CDN when promoted, else local.
export async function loadUsecasesSourceIntel() {
  const manifest = loadManifest();
  const usecases = manifest?.usecases;
  if (usecases?.repo && usecases?.sha) {
    return fetchFromCdn(usecases, 'content/usecases/_source-intel.json', 'loadUsecasesSourceIntel', 'usecases');
  }
  const localPath = join(contentDir, 'usecases', '_source-intel.json');
  if (!existsSync(localPath)) return null;
  return JSON.parse(readFileSync(localPath, 'utf-8'));
}
